### PR TITLE
add script to extract wind data

### PR DESCRIPTION
**Pull request by mhagdorn**
I have written a python3 script that uses xarray to load the reanalysis data from a set of netCDF files and produces the input file required by tephra2. A location and date is specified on the command line.

### CODE REVIEW

**Comment by ljc-geo** [comment]
Great! I am checking the script out now. Could you provide a list of dependencies needed to run the script?  Thanks!
 --Laura

**Comment by mhagdorn** [comment]
other than standard python3 library it needs xarray and numpy

**Comment by ljc-geo** [comment]
You mention the purpose of the script is to" load the reanalysis data from a set of netCDF files", which netCDF files are you using or referring to?  Sorry, I am just trying to understand your workflow. Thanks!

**Comment by mhagdorn** [comment]
xarray can handle any number of files to create a single dataset. The files need to contain uwnd vwnd and hgt. The location is specified on the command line using the -l option (either a float or in the format 1d2'3"N). The date is specified as yyyy-mm-dd. if there are multiple time slices with that date an average is formed. so I ran the script using

```
python3 extract_reanalysis_data.py *.nc -l 1°12\'60.00\"N 77°21\'59.99\"W -d 1997-1-1
```
where I have netCDF files `hgt_1997.nc`,  `uwnd_1997.nc`   and `vwnd_1997.nc`

hope this helps

**Comment by ljc-geo** [comment]
Hi  Magnus,

Are working with Julia? This script is a nice addition especially if someone is not familiar with perl.  I will  give it a try, again, and figure out what I need to do to merge it with the geoscience community codes version of tephra 2. Thank you!

Laura Connor
School of Geosciences​
University of South Florida
Tampa, Florida 33620

________________________________

**Pull request merged**
